### ISSUE TITLE
SQLBase driver similar to ORA is needed 

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#101]

**Comment by zhabis** [comment]
There is an issue with MsBuild/Nuget + SqlClient package: the build process does not put a proper `System.Data.SqlClient.dll` in the output of .NET framework target, the proper file is 233 kb, weheras a bad one is 255 kb. **Will probably need to copy the DLL by hand**
```
 [System.PlatformNotSupportedException] System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
```
https://stackoverflow.com/questions/49355530/system-data-sqlclient-is-not-supported-on-this-platform

**Comment by zhabis** [comment]
DONE, dll file inlined for now
