### ISSUE TITLE
Enable AzosApp with default config file mix-in (includes)

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#105]
Need to review how this is done in Sky and provide the similar behavior on a typical app.
Since includes use file-suystem and app, what app container should be used for includes?
we can limit this to NopApp/only local files.
The attribute like `process-include-levels=0` should be set to >1 to keep processing includes X times

Another solution would be to add `AppConfigLoader` class that would search for local config, then do includes in the scope of NopApplication. Then we can expose `GetEffectiveConfig()` method which we will feed into `new AzosApp(args, conf)`

**Comment by zhabis** [comment]
done:
```
app
{
  process-includes="_include"
 _include { file="./toy-mixin.xml" }
}
```
