### ISSUE TITLE
is LocalCache persistent if I use MMFPile ?

### ISSUE THREAD

**Issue by zubairalimansoor** [azist/azos#107]
is LocalCache persistent if I use MMFPile ? I tried , it saved data to disk but didn't load on starting again. Any idea ?

**Comment by zhabis** [comment]
The cache does not do this out of the box, howver you can easily load cache by iterating through pile object with foreach and loading them into cache on process restart. The MMF pile does NOT load everything in ram until segments are d-referenced using pointers

**Comment by zubairalimansoor** [comment]
Thank you for your answer. I tried as you suggested it worked :-)

Just one more thing wanted to ask, data from cache or Pile is stored to disk when WaitForCompleteStop() is called, so if application crashes before calling this function then data will be lost. So I think in order to make sure data is saved to disk, application should periodically keep on calling combination of these, correct ?

WaitForCompleteStop()
Start()

**Comment by zhabis** [comment]
You do not need to do that. The memory mapped files are written to by the OS, even if your process crashes, the OS manages on its own

**Comment by zhabis** [comment]
https://stackoverflow.com/questions/25172393/what-happens-to-mmaped-file-if-process-crashes
>There are exceptions which may or many not be relevant. Two mapped views of a file are guaranteed to remain coherent even if one program terminates abnormally, but this coherency does not extend to remote files or to files accessed concurrently using ReadFile/WriteFile.

**Comment by zubairalimansoor** [comment]
Hi,

I am using MMFPile with LocalCache to persist data and in case of crash , it can be reloaded. But I am facing problem,if application calls DisposableObject.DisposeAndNull(ref azosCache) before cloasing then only pointers are valid and data is reloaded correctly from disk. Could you please let me know what could be the problem ? it should reload data even when I don't call DisposableObject.DisposeAndNull(ref azosCache);

foreach(var entry in pile)
     {
            var buf = pile.Get(entry.Pointer) as byte[];
            Aver.IsNotNull(buf);
           ......
            Aver.IsTrue( entry.Type == PileEntry.DataType.Buffer );
     }

**Comment by itadapter** [comment]
could you re-phrase the question. you should call Dispose when you are shutting down as expected. when you run application again, data is mapped back into your address space from disk

**Comment by zubairalimansoor** [comment]
Thank you for your answer. 

when I call dispose then it works, but in case of crash if dispose is not called then it does not work, any solution to restore in case of crash ?Following is my code

            var azosCache = new LocalCache(NOPApplication.Instance);
            azosCache.Pile = new MMFPile(azosCache, "hw");//Pile owned by cache
            ((MMFPile)azosCache.Pile).DataDirectoryRoot = @"h:\azos";
            ((MMFPile)azosCache.Pile).AllocMode = AllocationMode.FavorSpeed;
            azosCache.DefaultTableOptions = new Azos.Pile.TableOptions("*")
            {
                CollisionMode = CollisionMode.Durable
            };

            azosCache.Start();

            orders_tbl = azosCache.GetOrCreateTable<string>("orders");

            foreach (var entry in ((MMFPile)azosCache.Pile))
            {

// here entry.Pointer is invalid if I don't call dispose or if application is crashed or killed

                Common.API.Types.Order order = ((MMFPile)azosCache.Pile).Get(entry.Pointer) as Common.API.Types.Order;
                if (order != null)
                {
                    PutResult? pResult;
                    object vv = orders_tbl.GetOrPut(order.ClOrdId, (t, k, _) => order, null, out pResult);
                }
            }

**Comment by zhabis** [comment]
The enumeration over pileEntries returns different types.
Are you checking Type property?
If your process crashes/terminates in the middle of writing of course it will corrupt memory.
You will see this behaviour if you hit STOP in VS debugger etc.. why is your process crashing?
```
 public struct PileEntry
  {
    public enum DataType { Object=0, String, Buffer, Link }
```

**Comment by zubairalimansoor** [comment]
Yes I am checking the types. Types are fine. Just the problem is when application stops abnormally in that case I cannot restore. Actually the purpose of using MMFPile is to restore data in case of normal restart or in case of any crash. So it means I have to make sure application terminates gracefully and there is no crash , in that case only it will restore data correctly.
