### ISSUE TITLE
Azos.Erlang

### ISSUE THREAD

**Issue by tymoor** [azist/azos#117]
Is this project (from:
jungerl,
  |> otp.net,
  |> NFX
) still alive? (hopefully?)

**Comment by zhabis** [comment]
@tymoor @saleyn  Erlang OTP is not in Azos, however it can be brought over fairly easy, the app structure needs to be refactored

**Comment by jdobrzanski** [comment]
I am running a cluster of erlang nodes and want to run a c# game servers along side them (long story).  Is bringing over Erlang OTP still possible?  Sorry for commenting on an old, closed issue.

**Comment by saleyn** [comment]
The version of Erlang .NET library is fully functional in the [NFX project](https://github.com/agnicore/nfx). You can use that one, as currently we didn't have a real need to justify porting it into Azos.
