### ISSUE TITLE
Add method to ArrowSerializer.RegisterSattelite() to register .Serialization settelite

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#134]
or extension method on Type similar to GetText(), like   type.RegisterArowSatellite()....

var asmFileName = System.Reflection.Assembly.GetExecutingAssembly().Location.Replace(".dll", ".Serialization.dll");
      var asm = System.Reflection.Assembly.LoadFrom(asmFileName);
      ArowSerializer.RegisterTypeSerializationCores(asm);

**Comment by zhabis** [comment]
Added `RegisterTypeSerializationSatelliteFor(asm)` and `RegisterTypeSerializationSatelliteForThisAssembly()`
