### ISSUE TITLE
Pile option to return Span<byte>

### ISSUE THREAD

**Issue by BillSobel** [azist/azos#138]
For use cases where Pile is managing byte arrays, an additional API to return a Span<byte> into the array vs allocating and returning a copy would be extremely useful (and performant).  Something along the lines of

Pile.GetSpan(pilePointer)

This would succeed if the serialized object was a byte array, and fail in all other cases (throw an exception)

**Comment by zhabis** [comment]
Pile must be thread-safe.
How to ensure segment consistency if we return a span without copy?
Say you get a span, then another thread deletes the underlying memory - you get corruption.

**Comment by BillSobel** [comment]
Typically such use would be for very short periods of time span is a stack only struct, can not be used as a reference, so the caller would be responsible for not mutating the pile after the span is received until the caller returns from the function in which is acquired the span<byte>.  I realize it may not be the normal use case, but the ability (even with the requirement you are responsible if someone else deletes the pointer or segment) would be a great performance in certain scenarios were the double copy could be eliminated.  In my current project I have to pull data from a pile pointer and compare it to new data, if the data does not match then I update the pile.  With this the compare could be done without making a copy, and I am find being responsible for other threads not deleting data while these operations are occurring. Hopefully that makes sense?

**Comment by zhabis** [comment]
It does, though a complex topic.  Maybe something like `GetDirectBufferUnsafe(ptr)` then the name of the method says it all. On the other hand, is it really worth it? If you need to compare, I would anyway keep object hash in your index (where you store PilePointers now), so say u get something like:  
```
{key: "ABC", Pointer: "N:1:fdeacedfb", hash: 34784401}
```
then instead of comparing from Pile you could compare new content for "ABC" entity using its hash, but again then you need to compute hash etc...

**Comment by BillSobel** [comment]
Well its about 4 billion items, so even adding the hash adds quite a bit of memory requirements to the system.  And yes, that api name makes sense if you are willing to add it.  Oh, and thank you for the Pile implimention to begin with. Dealing with so many small objects I knew the GC would never fly, this has been ideal!

**Comment by zhabis** [comment]
@BillSobel  ok, let me think a bit. I think we can add it to `DefaultPile` but not to general `IPile` interface as this method makes no sense in cluster, only local in-process.

Another consideration, I would return an `ArraySegment` as today Azos is dual-targeting .NET Fx which does not have Span<T> built-in yest (the System.Memory does tricks on NET fx vs Core). Your performance would not really suffer from ArraySegment which is a stack-returned struct.

**Comment by BillSobel** [comment]
Aw! My apologies, I forgot about .NET, so yes ArraySegment<> makes perfect sense so it remains portable. Sorry, been staring at core for a bit too long lately.  Also agree on DefaultPile, certainly a local only option.

**Comment by zhabis** [comment]
I have implemented 
```csharp
// Returns a raw ArraySegment pointing to direct segment chunk occupied by the object payload. 
// Only the payload is returned along with serializer flag which tells what kind of serializer was used.
// This method is rarely used, it is needed in special direct-memory access and is dangerous to use in general applications
// as the returned memory chunk pointed-to by ArraySegment can be mutated by another thread.
public ArraySegment<byte> GetDirectMemoryBufferUnsafe(PilePointer ptr, out byte serializerFlag)
```
This is going to go in the .X minor release either later today or tomorrow.
Many unit tests need to be constructed to test it

**Comment by BillSobel** [comment]
Fantastic, I will grab the latest and bang on it. 
Thank you!

**Comment by zhabis** [comment]
Its on WIP  here 2d14d576dd0537e3a96170d7d40c11efd2a21401

**Comment by zhabis** [comment]
I have added Subarray<T> class which can also help your case to avoid dbl copy on put. It is similar to ArraySegment, but it is a mutable class , so it does not get boxed in put(object), you can call .Set(array,size)

Subarrays always start on index zero (unlike array segments).
This way you can put Subarrays of your exyternal array directly into byte[] in pile without extra copies, e.g. if you have a memory stream which allocated 1000 bytes, the payload is only 20 bytes, you can use subarray(memorystream.getBuffer(), memorystream.Position)

**Comment by zhabis** [comment]
Assign @BillSobel  as tester

**Comment by itadapter** [comment]
The package was released as 1.0.507.2

**Comment by BillSobel** [comment]
How often do you push to NuGet (e.g. when would this build likely show up there)?

**Comment by zhabis** [comment]
@BillSobel  Nugetr 1.0.507.2 already has it (the added GetDirectMemoryBufferUnsafe(PilePointer ptr, out byte serializerFlag)) also check out the unit test
https://github.com/azist/azos/blob/master/src/testing/Azos.Tests.Nub/Pile/BasePileTests.cs#L92:L110

**Comment by BillSobel** [comment]
Thanks, the update showed up for me right after I asked. Working great, it removed the last required data copy on my hot path to storage!

**Comment by zhabis** [comment]
@BillSobel  How much speed improvement did you get %-wise?

**Comment by BillSobel** [comment]
Honestly its hard to directly measure as the main benefit comes from reduced load on the GC. It looks to be close but not quite 1% of overall throughput (the system is ingesting and processing data at about 1m eps, so every 1% is about 10k improvement in speed)

**Comment by zhabis** [comment]
@BillSobel  do you use server mode GC? it can help allocation speed 2x-4x

**Comment by BillSobel** [comment]
Server mode, yes absolutely.
