### ISSUE TITLE
Proper Pile POCO Examples

### ISSUE THREAD

**Issue by SwiftyZA** [azist/azos#146]
Could we somehow get a proper end to end example of how to load a large amount of POCOs into a pile and running queries on the Pile? I've been scouring the source to try and make heads or tails of how its meant to be done, but to no avail.

**Comment by zhabis** [comment]
Seen this: 
https://github.com/azist/azos/tree/master/src/Azos/Pile    

Unit tests:
 https://github.com/azist/azos/tree/master/src/testing/Azos.Tests.Unit/Pile
"Querying":
https://github.com/azist/azos/blob/master/src/testing/Azos.Tests.Unit/Pile/CacheTest.cs
