### ISSUE TITLE
Why DBG log does not show CriticalAlert, while having min-level=Error?

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#171]

**Comment by erxdkh** [comment]
```
log
{
  sink
  {
    name="gen"
    type="Azos.Log.Sinks.CSVFileSink, Azos"
    path=$(/$log-path)
    file-name="{0:yyyyMMdd}-$(/$name)-$($name).csv.log"
  }
  sink
  {
    name="dbg"
    type="Azos.Log.Sinks.DebugSink, Azos"
    path=$(/$log-path)
    file-name="{0:yyyyMMdd}-$(/$name)-$($name).log"
    min-level=Error
  }
}
```

**Comment by zhabis** [comment]
f2bd2ffe05ffade23322a19ce350172851ac8577 Fixed DbSink error nullref exception

**Comment by jkosherx** [comment]
,bdcbd39f-d57a-42ee-b86f-3bd8ab2607ae,9121afc9-72ff-48a1-b6e7-ac6cda20b26c,Error,20190730-122026,DXPIT-SFOAPPV01,WAVE,Azos.Wave.Filters.ErrorFilter,"[Azos.Wave.FilterPipelineException] > realip > session >  [Azos.Wave.MvcActionException] Controller action body: 'Erx.Business.Api.Controllers.Financial.Tran'.'list'. Exception: [Erx.Business.ErxBusinessException] Could not apply filter `TransactionListFilter`: [Azos.Data.DocValidationException] Schema: 'Filters::TransactionListFilter'; Filter Criteria Invalid. You must specify at least one of the following filtering criteria: MemberNumber, PreviousCardId, RxNumber, or RxDate. Trace: \r\n    at Erx.Business.Api.Controllers.ApiProtocolController.<ApplyFilter>d__1`1.MoveNext() in C:\Repos\Business\src\Erx.Business.Api\Controllers\ApiProtocolController.cs:line 43",0,,"{""$ip"":""192.168.48.118:54908"",""$ua"":null,""$mtd"":""POST"",""$uri"":""http:\/\/dxpit-sfoappv01:8100\/tran\/list"",""$ref"":null,""$stat"":""400\/Bad Request \/ Data validation""}","Azos.Wave.FilterPipelineException::> session >  [Azos.Wave.MvcActionException] Controller action body: 'Erx.Business.Api.Controllers.Financial.Tran'.'list'. Exception: [Erx.Business.ErxBusinessException] Could not apply filter `TransactionListFilter`: [Azos.Data.DocValidationException] Schema: 'Filters::TransactionListFilter'; Filter Criteria Invalid. You must specify at least one of the following filtering criteria: MemberNumber, PreviousCardId, RxNumber, or RxDate. Trace: \r\n    at Erx.Business.Api.Controllers.ApiProtocolController.<ApplyFilter>d__1`1.MoveNext() in C:\Repos\Business\src\Erx.Business.Api\Controllers\ApiProtocolController.cs:line 43"
,c75b2789-32a3-4386-9ca2-1610a05c11e0,bdcbd39f-d57a-42ee-b86f-3bd8ab2607ae,Error,20190730-122026,DXPIT-SFOAPPV01,Log,dbg,"Message bdcbd39f-d57a-42ee-b86f-3bd8ab2607ae delivery failed over from destination 'dbg' to 'fail'. Average processing latency of failed destination '0'",0,,,"System.NullReferenceException::Object reference not set to an instance of an object."
,5d747516-d0b3-4f70-a78f-a4c43606a46d,5b6a74da-868a-4880-bb21-2c28f025b789,Error,20190730-122026,DXPIT-SFOAPPV01,WAVE,Azos.Wave.Filters.ErrorFilter,"[Azos.Wave.FilterPipelineException] > realip > session >  [Azos.Wave.MvcActionException] Controller action body: 'Erx.Business.Api.Controllers.Financial.Tran'.'list'. Exception: [Erx.Business.ErxBusinessException] Could not apply filter `TransactionListFilter`: [Azos.Data.DocValidationException] Schema: 'Filters::TransactionListFilter'; Filter Criteria Invalid. You must specify at least one of the following filtering criteria: MemberNumber, PreviousCardId, RxNumber, or RxDate. Trace: \r\n    at Erx.Business.Api.Controllers.ApiProtocolController.<ApplyFilter>d__1`1.MoveNext() in C:\Repos\Business\src\Erx.Business.Api\Controllers\ApiProtocolController.cs:line 43",0,,"{""$ip"":""192.168.48.118:54908"",""$ua"":null,""$mtd"":""POST"",""$uri"":""http:\/\/dxpit-sfoappv01:8100\/tran\/list"",""$ref"":null,""$stat"":""400\/Bad Request \/ Data validation""}","Azos.Wave.FilterPipelineException::> session >  [Azos.Wave.MvcActionException]

**Comment by jkosherx** [comment]
Still an issue

**Comment by zhabis** [comment]
CLOSED. This will be addressed with next Nuget package release
