### ISSUE TITLE
LocalCache does not have parameter-less constructor but docs suggest that it does

### ISSUE THREAD

**Issue by ProductiveRage** [azist/azos#175]
In the "Examples" / "4 - Caching" section of the readme here:

[https://github.com/azist/azos/tree/master/src/Azos/Pile](https://github.com/azist/azos/tree/master/src/Azos/Pile)

.. the first line of code is:

`var cache = new LocalCache();`

However, the LocalCache class doesn't have a parameter-less constructor and so this will not compile.

I looked in the unit test code and found that it can instantiated by providing NOPApplication.Instance as the IApplication reference - is it appropriate to use that in production code? If so, would it seem like a reasonable idea to add a parameter-less constructor to LocalCache that sets the IApplication reference to NOPApplication.Instance in order to make the library as easy as possible for people to consume?

It looks like the change that removed the constructor was this one, from Nov 2018:

[https://github.com/azist/azos/commit/c3e4fb70fddb56e98e51456944722d9ab8400c32#diff-3f0da1450df24fdeafb008fc099be536](https://github.com/azist/azos/commit/c3e4fb70fddb56e98e51456944722d9ab8400c32#diff-3f0da1450df24fdeafb008fc099be536)

**Comment by itadapter** [comment]
LocalCache is application component. It can only run in scope of app chassis.
You can pass `NOPApplication.Instance`  but this needs to be done explicitly to signify the intent of using that particular application that will not render any services such as logging and component runtime management.
