### ISSUE TITLE
Add ability to pass Authorization header via a query parameter? (or URI) how do we protect a GET resource when custom header can not be added?

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#209]

**Comment by zhabis** [comment]
This should not be used a s a general-purpose solution, as this is a bad practice:
* not secure
* can be bookmarked
* URIs get written into logs

You might need to consider using a valet key instead, which only grants one access to a certain resource. The generation of this key and use patterns are out of the general purpose security scope
