### ISSUE TITLE
operator overloading for PilePointer

### ISSUE THREAD

**Issue by furesoft** [azist/azos#21]
add operators to PilePointer like

`!ptr` dereferencing

**Comment by zhabis** [comment]
Would need to be on [Piled](https://github.com/azist/azos/blob/master/src/Azos/Pile/Piled.cs), as `PilePointer` does not contain what pile the pointer is from

**Comment by zhabis** [comment]
Added binary operator & in commit c079e71:
```CSharp
//PilePointer.cs
public static object operator &(IPile pile, PilePointer ptr)
{
   return pile.NonNull(nameof(pile)).Get(ptr);//->     var x = pile&ptr;
}

//Usage:

//using Get
var obj = pile.Get(ptr);

//using operator
var obj = pile & ptr;
```
