### ISSUE TITLE
Need API Tunnel handler -to tunnel all traffic unchanged from certain route to sub-routes

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#217]
Need API tunnel for example:
```
/systmx/.......
```
will send all payload to 
```
other-uri/anotherpath
```
and get the results back

This is needed to tunnel things like Mule internal API

However, we do ned to have ability to add filters like authentication/authorization etc...
so it is not 100% transparent

**Comment by itadapter** [comment]
Voting for names:
ApiRouter ServiceRouter ServiceRelay  ApiGateway  ServiceGateway ApiTunnel ApiRelay
