### ISSUE TITLE
Q: Pile: TryGet()

### ISSUE THREAD

**Issue by KingKnecht** [azist/azos#22]
I'm missing a` bool TryGet(ptr, out object)`.
Is there a reason why there is only a Get(ptr) which throws an (slow) exception in case the Ptr is invalid?

**Comment by zhabis** [comment]
Never had a need to de reference a possibly invalid pointer. Can you describe your case?
This an certainly be added

**Comment by KingKnecht** [comment]
If the PilePtr is part of another object, let's say as an ID. And the object gets distributed to multiple threads or computers in a network, then it is possible that one thread/computer has requested a deletion of the object and the serialized data in the pile -> the PilePtr, stored as an Id, in all distributed objects is invalid now.
If now a thread/computer wants to update the object (with the invalid PilePtr-Id) the Get() would fail, because it has  already been deleted. 
A fast TryGet() would be nice here.
Of course additional checks are required on application level to make sure it's really the appropriate data from the pile, because there could be already a new object stored on the same address.

Does this make any sense to you?

**Comment by zhabis** [comment]
yes that makes sense, do you want to add the method and send pull req
or do you want me to add it?

**Comment by zhabis** [comment]
Will do this but in milestone 2 (past Feb 2019)
