### ISSUE TITLE
Need to retest JSON DateTime handling, specifically UTC, Re #80 and .AsDateTime(....)

### ISSUE THREAD

**Issue by zhabis** [azist/azos#221]
AsDateTime(AssumeUTC) does not work for dates with "Z"????

**Comment by zhabis** [comment]
This is related to #80

**Comment by itadapter** [comment]
Nuget 1.0.537

**Comment by zhabis** [comment]
Appveyor tests fails because of timezone, there is something wrong:

![image](https://user-images.githubusercontent.com/39680879/71537954-8877bf80-28f1-11ea-8800-708099e51641.png)

**Comment by itadapter** [comment]
Done 7f22d9c17c1969644d185555d8a1cb4c7a931b31
