### ISSUE TITLE
Add optional character to DataDoc field value list validator:  [0]1:code1; [0]2:code 2

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#223]
We need to treat "1" the same as "01". This has to be optional and maybe use pattern matchig for lookup?  For example:   i want to show 01 in drop down, but if user submits "1" it should still work

**Comment by erxdkh** [comment]
@foliage71  see

**Comment by zhabis** [comment]
The issue is done in 6961fbe

You can now do like this:
```
 [Field(valueList: "1|01: code one; 2|02|two: code two")]
 public string Prop...
```

**Comment by zhabis** [comment]
@foliage71  @mmalev This was added for NCPDP specifically, use "|" do delimit alternate keys:
```
 valueList="
     1|01: Normal claim type,
     2|02: Type two specifier
"
```
