### ISSUE TITLE
DataDoc.Schema.Field.ValueLists - hardcoded AND dynamic - which one wins?

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#234]
Shouldn't dynamic list take precedence over hardCoded one?

**Comment by zhabis** [comment]
@foliage71 When you have a case when both `valueList` is defined and `GetDynList()` returns a list, the dynamic list will take a precedence over `valueList` defined using a `[Field]` attribute.

You may return `null` to indicate that the field has no dynamic list (then `valueList` (if any) will be checked against; or empty `JsonDataMap` which will excuse the field of interest from any checks even if the `valueList` is defined in `[Field(...valueList...)]` way

@foliage71 @mmalev Specifically for NCPDP case:
```csharp
  public override JsonDataMap GetDynamicFieldValueList(Schema.FieldDef fdef,
                                                        string targetName,
                                                        string isoLang)
  {
      if (fdef.Name==nameof(YOURFIELD) && tagetName.EqualsOrdIgnoreCase(LERX))
        return m_LookupLogic.GetYOURFIELDValueList(.......);
  }
```
