### ISSUE TITLE
How to specify TRUN pattern match with "NOT", e.g. methods that DO NOT match xyz*

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#242]

**Comment by erxdkh** [comment]
Not only methods, but all other entities, namespaces etc..
Maybe we a character like `!` can be used to soecify the inverse behavior, like: `methods=*Serilizer*;!*Json*`

**Comment by zhabis** [comment]
You can use `~Pattern*` for "not" which gets "and"ed with other conditions
