### ISSUE TITLE
Api Documentation - what TargetName is the documentation generated for?

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#245]
We might need to generate API doc for some targets ONLY for authorized user as we may not want to disclose some details to general pub endpoint

**Comment by erxdkh** [comment]
Re: @foliage71

**Comment by zhabis** [comment]
You can use `DataTargetName` property of `ApiDocGenerator` which you allocate in `MakeDocGenerator()`. You can also check `dataContext` by overriding `CheckDataContext(string)`
