### ISSUE TITLE
Do data Documents cover ref cycle for Validation and DI?

### ISSUE THREAD

**Issue by itadapter** [azist/azos#287]
This is not a bug an generally Docs should not form cycle as they are DAGs, however what if there are cycles introduced in code, will the cycle just hang? The check will certainly introduce extra time, so should we handle this in data docs at all or just ignore?

Example: a family object that has siblings, which point to Person, which in term points to Family. Yes, this is strange to use in a business app but who knows..

**Comment by zhabis** [comment]
Starting Azos.Tests.Nub::Azos.Tests.Nub.DataAccess.DocRecursiveGraphTests ...
  - NoRecursion [OK]
  - Recursion
**Process is terminated due to StackOverflowException.**
```csharp
   [Run]
    public void Recursion()
    {
      using (var app = new AzosApplication(null, null))
      {
        var family = new Family();
        family.People = new List<Person>();
        family.People.Add( new Person
         {
           Family = family,
           PersonName = "Alex"
         }
        );
        app.InjectInto(family);//still no errors
        family.Validate();//still no errors
      }
    }

    public class Family : TypedDoc
    {
      [Inject] ILog m_Log;
      [Field] public List<Person> People{ get; set;}
    }

    public class Person : TypedDoc
    {
      [Field] public Family Family { get; set; }
      [Field] public string PersonName { get; set; }
    }
```

**Comment by zhabis** [comment]
rel #290

**Comment by zhabis** [comment]
Added cycle detection with `ObjectGraph.Scope()` graph state machine see unit tests `ObjectGraphTests.cs`
