### ISSUE TITLE
Question: Is it possible to create reference cycles in DI using attributes?

### ISSUE THREAD

**Issue by itadapter** [azist/azos#290]

**Comment by zhabis** [comment]
rel #287, it is possible, specifically if you implement custom DI handler.
The practical probability of this happening is very low, however this does happen with Data doc if they have cycles (again this is almost a non-existing case). The question is - what do we do about this if anything at all, as checking does create some minimal penalty which is absolutely insignificant in 99% aplications

**Comment by zhabis** [comment]
See #287. This is addressed using `ObjectGraph`
