### ISSUE TITLE
Object Pile Raw Memory Allocator Question

### ISSUE THREAD

**Issue by GenkoP** [azist/azos#296]
I am using v1.4.0. To avoid some serialization I made some test with Object Pile raw memory allocator to see the behaivior. The code that use is: 
```
            var localCache = new LocalCache(NOPApplication.Instance);
            localCache.Pile = new DefaultPile(localCache);
            localCache.Pile.AllocMode = AllocationMode.FavorSpeed;
            localCache.DefaultTableOptions = new TableOptions("*")
            {
                CollisionMode = CollisionMode.Durable,
            };

            localCache.Start();
            var cache = localCache.GetOrCreateTable<int>(Guid.NewGuid().ToString());

            var list = Enumerable.Range(0, 300).Select(x => new byte[35000]);

            for (int i = 0; i < 1000000; i++)
            {
                int key = 1;
                foreach (var item in list)
                {
                    cache.Put(key, item);
                    Console.WriteLine($"Key => {key}");
                    key++;
                }
                Thread.Sleep(1000);
            }

            localCache.WaitForCompleteStop();
            localCache.Dispose();
            //or just 1 line instead of the 2
            DisposableObject.DisposeAndNull(ref localCache);
```
When i start it, after few seconds, my memory on my computer is increased to about 800mb. After some time my memory is decreased to 100md. That on every cycle. It seems that GC clean this memory. When i try predefined byte[], then this issue does no exists. Maybe there is reference check when put same byte[] instance with same key. But when i put different instances, there is same behavior.

Do I miss some configuration to my caches to allow putting on byte[], without to grow my memory? 
 
This issue does not exists, when I use CLR objects. My case is to keep in cache a lot of objects more than week. And at the end, it is need frequently updates (every 1-3 seconds)

**Comment by zhabis** [comment]
@GenkoP I think what you see is allocation of very many `byte[]` in this line: 
```
var list = Enumerable.Range(0, 300).Select(x => new byte[35000]);
```
For every iteration it creates a new byte[] and GC then cleans it in a few seconds/minutes.
This behavior is not connected to Pile at all.

What you might want to do instead is add small objects but many of them and just keep them in pile, as your test is mostly testing CLR GC and not pile

**Comment by GenkoP** [comment]
@zhabis So if I use Dictionary<int, byte[]> instead of Pile I will have the same behavior.

```
            var cache = new Dictionary<int, byte[]>();
            var list = Enumerable.Range(0, 300).Select(x => new byte[35000]);

            for (int i = 0; i < 1000000; i++)
            {
                int key = 0;
                foreach (var item in list)
                {
                    cache[key] = item;
                    Console.WriteLine($"Key => {key}");
                    key++;
                }
                Thread.Sleep(1000);
            }

```

**Comment by itadapter** [comment]
You are allocating byte[] in a deferred fashion when u walk Enumerable, so you allocate 300 items 1000000 times.  Yes, you can put them in dictionary in which case memebr will keep growing and never shrink.  This test is about testing large arrays and CLR.  If you need to test pile, then allocate many (tens -hundreds of millions) of CLR objects and store them in cache. And in dictionary and see that your dictionary version would stop the process for 4-5 seconds very soon, whereas Pile will never do that

**Comment by zhabis** [comment]
Do this:
```
class Person
{
  public string A{get;set;}
  public int B{get;set;}
  public bool C{get;set;}
  public long D{get;set;}
}


           localCache.Start();
            var table1= localCache.GetOrCreateTable<int>("table1");

            Parallel,For((0, 50_000_000;  i=>{
               table1.Put(i, new Person{ ......  }); 
            });
```
