### ISSUE TITLE
Question about app containers nestings

### ISSUE THREAD

**Issue by binfomater** [azist/azos#3]
*I have question about nesting of app containers in v5 (per your email i ask here)
how is it that services use App. global accessor when context is nested?
I don't get what first services (the ones that booted under first) shall see upon 2nd container launch - 2nd app scope?
Is this a glitch? 
I do buy this static class pattern for "ambient context" but perplexed about nesting.*

**Comment by zhabis** [comment]
in process of major refactoring that will rectify your issue as well

**Comment by zhabis** [comment]
The refactoring is done, you can pull and start using,I am still working on unit tests update

**Comment by itadapter** [comment]
This is DONE and tested.
