### ISSUE TITLE
CacheExtensions - FetchThrough() add ability to put result back into multiple tables with different keys

### ISSUE THREAD

**Issue by itadapter** [azist/azos#310]

**Comment by itadapter** [comment]
DONE

**Comment by itadapter** [comment]
The problem is that the cache.Put(ptr) used for secondary table puts get re-used for a totally different item, when the same ptr is put into table A and table B, say table B gets expired, it deleted ptr pointed to by B, so A still points to it, but the system re-uses it for storing a different value, consequently,  key in table A  resolves to a completely different pointer because the space is re-used.

This is a very dangerous bug that was introduced with the fix performed recently (#310 #311 )

**Comment by itadapter** [comment]
# Example
Say there are two tables: A and B that store Car.
```
  var ptr = tblA.Put((name: "Alex", age: 25), new Car("Buick"));
  tblB.Put(12345, ptr);//Buick is no indexed by the 12345 key as well
```
Now, the tblB value expires, and it deletes the pointer pointing to "Buick".
tblB does not have a record, but tblA still does, pointing to invalid memory block, HOWEVER
someone else inserts something into tblC, and it just so happens that the value for "Airbus 320" (not a Car even)
gets inserted physically at the same pointer that tblA  still points to.

Now tblA, points to not even a Car but Airplane "Airbus 320".
The data is logically corrupted now.

**Comment by zhabis** [comment]
> the cache.Put(Pointer) probably needs to take ownership and not delete the key if the key was inserted with existing pointer, that is, put(pointer) should not own pointer, hence it should not delete the value from pile on key delete; whereas put(key) which generates its OWN pointer on insert, MUST OWN that pointer and delete it on key delete.

The fix is not a fix, but yet another defect. What if the tblA expires first (and owns that pointer, thus deletes it), then tblB now contains an entry pointing to bad data. Same problem exists.  This can not be fixed without reference counting mechanism which we can not afford at this point (too complex for very questionable benefit)

**Comment by zhabis** [comment]
What can be done is that `fFilter` is required IF `extraPut` is specified, where fFilter has to re-check the per-key aptitude of the fetched value, however this is very dangerous still as there is no guarantee that fFilter will be implemented properly. What is someone else call tbl.Get() without the filter. The cache is still corrupted. Consequently it is a BAD idea to return a pointer from put and re-index it somewhere else. Only the keys can be re-indexed. Not the value by itself.

**Comment by zhabis** [comment]
bb66a99     You can not use pointers. Use secondary indexes. Such is the verdict
