### ISSUE TITLE
UInt32 property config with HEX prefix error?

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#332]
ERROR: [Azos.AzosException] App root module initApplication error: [Azos.Conf.ConfigException] Error applying config attribute to property/field 'Era' for the instance of 'Azos.Data.Idgen.LocalGdidGenerator'. Exception: Value from 'era' could not be gotten as type 'System.UInt32'

era=0x01

**Comment by itadapter** [comment]
DONE
