### ISSUE TITLE
WEBCONSOLE -- Add ASCON wave Handler for remote admin via web bypassing WebMan

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#341]

**Comment by itadapter** [comment]
WIP
![image](https://user-images.githubusercontent.com/2273574/91109352-b6600000-e648-11ea-9daf-d1f779897d8c.png)

**Comment by itadapter** [comment]
Since the service is used within the enterprise without SSL, passing an Authorization header in plain text is not a secure option. The remote terminal WebConsole controller needs to be equipped with the Digest authentication method to prevent hijack/replay attacks on the token.

**Comment by itadapter** [comment]
The best solution is still to use HTTPS, and limit the allowed traffic ONLY from NetScaler (which has a certain IP) which mandates HTTPs (even on internal network), the limit can be set using a filter or separate listener

**Comment by sergey-msu** [comment]
the end is near ;)

**Comment by zhabis** [comment]
Deployed to prod
