### ISSUE TITLE
Log chronicles - do we want to add DevOpsPermission to log access in non-Dev environment?

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#380]
Should this be environment based, or should it be based on the caller origin? e.g. require DevOps only from external calls?
Who is going to determine this (e.g. caller is out-of-network)?

So today this can be done with `SecurityFilter` based on pattern match of the caller subnet pattern?

**Comment by zhabis** [comment]
The proper way of handling this is to use `SecurityFilter` like suggested, and use a "YourCompanyNetworkMatch()" which you can implement in your assembly for ypour enterprise. Typically local nets us: 10*, 172*, 192*, local private networks, however your company may be different. You can then demand an extra permission as a DevOps() permission

**Comment by zhabis** [comment]
The `ChroniclePermission` has been modified with more granular access rights 
```csharp
  /// <summary>
  /// Controls the access level to chronicle service
  /// </summary>
  public enum ChronicleAccessLevel
  {
    Denied  = AccessLevel.DENIED,

    /// <summary>
    /// Can emit (write) messages, basically using the service as a client
    /// </summary>
    Emit    = AccessLevel.VIEW,

    /// <summary>
    /// Can browse the written chronicles, this is HIGHER access level than Emit
    /// </summary>
    Browse  = AccessLevel.VIEW_CHANGE,

    /// <summary>
    /// Can also archive (delete) old data
    /// </summary>
    Archive = AccessLevel.VIEW_CHANGE_DELETE
  }
```
