### ISSUE TITLE
MinIdp: supress rights warning for SYS-level login when role is EMPTY (not assigned)

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#393]
{
  "Gdid": "0:2:370980",
  "Guid": "4d4b10f2-c040-4327-a672-19a459e72c8a",
  "App": "rtpb",
  "Type": "Warning",
  "Source": 219,
  "UTCTimeStamp": "2020-12-24T15:24:19.874Z",
  "Host": "ESSMIX-WD001",
  "From": "MinIdpSecurityManager@124.MakeOkUser",
  "Topic": "Sec",
  "Text": "Rights could not be read for `IDPasswordCredentials(root)`@`api`"
}

**Comment by zhabis** [comment]
WIP/rtm
