### ISSUE TITLE
The MinIdp store should use Impersonation for command execution, because we do not want to grant extra rights for general IDP access

### ISSUE THREAD

**Issue by itadapter** [azist/azos#401]
An IDP client store uses a low-privileged service account to access (authenticate on and consequently get authorized) the upstream IDP server. We do not want to grant that service account too many rights as it is generally not a good practice because it is against the  principle of the least privilege.

On the other hand, we need to execute management commands on the upstream IDP server. The management commands, specifically for an IDP, demand the maximum system-level access rights. Thus, there is a conflict with the previous stipulation.

The solution is to impersonate the caller of the upstream IDP service as the current caller, just for the purpose of running the admin commands. This makes sense because these commands should be executed on behalf of the specific administrator, not on behalf of service account.

**Comment by itadapter** [comment]
Related #400, assigning @JohnPKosh FYI

**Comment by zhabis** [comment]
```csharp
  var impersonate = Ambient.CurrentCallUser.MakeSysTokenAuthHeader();
          var call = await one.Call((http, ct) => http.Client.PostAndGetJsonMapAsync("exec", new { source = stepSrc }, requestHeaders: impersonate.ToEnumerable()));
```
