### ISSUE TITLE
Design LAR format: provide recovery block data for reading partially corrupted log stream *.LAR files

### ISSUE THREAD

**Issue by itadapter** [azist/azos#406]
The data stream is to be 16-byte boundary aligned with block prefix code.
If the file gets corrupted, the reader may fast forward to the nearest hex-aligned boundary containing magic

The below example uses "ABBA" as magic, every line = 16 bytes.
Because this does add overhead we can emit align codes no sooner than for example 1024 bytes, therefore
the data loss might affect more than one message, but it is a tradeoff.

The [GUID hash] is a 4 byte integer hash of the 1st message guid. This is needed to ensure that the boundary does not 
coincidentally get detected from the message data 
```
  AB BA [GUID hash]
  ........................
  ........................
  ........................
  .............0000
 AB BA[GUID hash]
  ......................
  ......................
```

**Comment by zhabis** [comment]
But since you can not know if the delimit boundary exists in data anywhere this method is still susceptible to corruption.

**Comment by itadapter** [comment]
What should be written is boundary-alligned 2 byte magic then  LEB128 - encoded ulong of thAT position in the file - this way the probability of corruption is way lower than using hard-coded ID

**Comment by JohnPKosh** [comment]
See special thanks section of README.md here https://github.com/rzubek/mini-leb128
Thought you would appreciate

**Comment by itadapter** [comment]
@JohnPKosh the idea of using external compression/encryption via a `Encryption(Compression(Stream(AWS-S3)))` is not going to work because those **streams are not random-access** streams - you can not `Seek()` over a compressed stream. Furthermore, from what I recall Amazon S3 supports random access, but others may not, therefore it would make sense to perform Big Data deferred analysis jobs over files downloaded to local FS for processing or use something like HDFS - all of this adds complexity, specifically for the corporate environment where it gets problematic.

Random access archive file seek capability is a VERY important one for big-data deferred analysis applications where we need to "jump to" specific pointer upon dereference. e.g. - why would I need to read the whole 1TB archive if there are only, say 100 records that satisfy my "problematic customer" index search? It would make way more sense to seek 100 times to those 100 matches and materialize them as `TEntity`  instances. The problem, however is that those `TEntity` entries are NOT compressible 1 by 1 as it does not make any sense to compress short messages 1 by 1. Instead we need to make an archive stream consist of pages and make pages compressible and encryptable, then when we read a page - we take it in memory. A page may be, say 4Kb in length holding X `TEntity` entries.

**Comment by itadapter** [comment]
```
Started 01/22/2021 20:54:32
Starting Azos.Tests.Nub::Azos.Tests.Nub.IO.Archiving.DefaultVolumeTests ...
  - Write_LogMessages Did 64000000 in 10.6 sec at 6,058,987.86 ops/sec
CLOSED all
[OK]
64 million unique logging messages, every 16th message has an exception (on purpose)
6 mil writes a second into data file and 1 index
data file is 9.2 Gb   index is 1.8 Gb
```

**Comment by itadapter** [comment]
@JohnPKosh  Linux Archiving tests are passing
![VirtualBox_octodvu20_20_02_2021_19_33_14](https://user-images.githubusercontent.com/2273574/108612053-c3209f00-73b2-11eb-8ee8-3578b47874c3.png)
