### ISSUE TITLE
Create `CodeFlow` and `DistributedCallFlow` implementations of ICallFlow

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#408]
Refactor this:
```csharp
 private struct XXXXXXXXXXXXXFlow : ICallFlow
    {
      public XXXXXXXXXXXXXXXXFlow(Guid guid) => m_Id = guid;
      private Guid m_Id;
      public Guid ID => m_Id;

      public string CallerAddress => "code";
      public string CallerAgent => System.Reflection.Assembly.GetExecutingAssembly().FullName;
      public string CallerPort => System.Reflection.Assembly.GetEntryAssembly()?.FullName;

      public IEnumerable<KeyValuePair<string, object>> Items => Enumerable.Empty<KeyValuePair<string, object>>();
      public object this[string key] { get => null; set { } }
    }
```

**Comment by erxdkh** [comment]
Make sure that ITEMS is implementaed by using concurrent dictionary whoch is lazily allocated, this is because the downstream services may need Items, and noone can disregard the service provided by ICallFLow

**Comment by itadapter** [comment]
Why is this not a Stack?

**Comment by erxdkh** [comment]
Related #409

**Comment by erxdkh** [comment]
Can we extend this for `IDistributedCallFlow : ICallFlow` with stack frames concepts, so that the caller may query for that interface optionally, while others can use ICallFlow which points to most calling stack frame.

However, what needs to be determined is what happens when an inner caller decides to establish a IDistributedCallFlow?? maybe the distributed call flow then supersedes the flat one.. this needs to be discussed

**Comment by itadapter** [comment]
Added `DistributedCallFlowFilter `
