### ISSUE TITLE
Log.Message.InitFileds is very slow due to Computer.HostName using environment.MachineName

### ISSUE THREAD

**Issue by itadapter** [azist/azos#410]
This is a perfect example of "one does not need to know the details"...as propounded by encapsulation.
The `Environment.MachineName` internal get accessor causes a cross-lock between threads, why??? and causes the log message `.InitDefaultFields` to lock out parallel execution

**Comment by itadapter** [comment]
After this fix, performance jumped from 250K/sec to 6 M/sec

**Comment by JohnPKosh** [comment]
That is definitely one of those "details" that needs understood when utilizing in hot code paths. It pays to be fastidious. Good catch, let's keep fishing for more.

**Comment by itadapter** [comment]
just opened #414 kinda of similar oversight that is easy to miss. I added extra WARNING text to Atom.Encode as well
