### ISSUE TITLE
DefaultVolume private writeData method needs `leaveOpen: true` in constructor

### ISSUE THREAD

**Issue by JohnPKosh** [azist/azos#411]
m_TempMemoryStream is closed on line no. 394 through 398 because it is missing the leaveOpen: true constructor parameter.

Should be:

      //1 - compress
      if (m_Metadata.IsCompressed)
      {
        m_TempMemoryStream.SetLength(0);
        using (var zip = new GZipStream(m_TempMemoryStream,
                                        m_Metadata.CompressionScheme
                                                  .EqualsOrdIgnoreCase(COMPRESSION_SCHEME_GZIP_MAX) ?
                                                    CompressionLevel.Optimal :
                                                    CompressionLevel.Fastest, **true**))
        {
          zip.Write(data.Array, data.Offset, data.Count);
        }
        data = new ArraySegment<byte>(m_TempMemoryStream.GetBuffer(), 0 , (int)m_TempMemoryStream.Length);
      }

**Comment by itadapter** [comment]
good catch
