### ISSUE TITLE
Add unit test coverage for Archiving.IPageCache and encryption; perform encryption+compression perf testing

### ISSUE THREAD

**Issue by itadapter** [azist/azos#422]

**Comment by zhabis** [comment]
Perf results:

Encrypt | Compress | Count | Size | Write | Read | Search
---- | -----| ----    |  -----      |  ----          |  ----         |  --- 
  none     |  none       |   16m |   34 Gb   |  770k/sec |  1.1m/sec | 14.5 sec
AES |   none     |   16m |   34 Gb   |  140k/sec |  597k/sec | 26.7 sec
AES |  GZIP |  16m  |  3.7 Gb  |   367k/sec |  920k/sec | 17.4 s

**Comment by zhabis** [comment]
Need to test case where encryption key changes and written data can not be read back

**Comment by JohnPKosh** [comment]
Tested read on my 6 year old PC using aes1 settings in CryptoManager in WinForms test rig (no test runner overhead):
Did 16,000,000 found 228 in 7.9 sec at **2,031,489.90 ops/sec**.
More than double testrunner unit test at 741,683.44 ops/sec what my PC was able to read.
