### ISSUE TITLE
Add  IO.Archiving.ParallelReadingStrategies extension methods

### ISSUE THREAD

**Issue by itadapter** [azist/azos#429]

**Comment by zhabis** [comment]
Reading using `ParallelProcessVolumeBatchesStartingAt` archive or 16,000,000 `Log.Message` instances. Every message is 2,260 bytes on average.

Compression | Serialization|CPU | Streams | Time | Size | IO
-------------- | -------------|-----| -------| -------|----|----
  none | none | 75% |16 | 4.2 s | 34.5 gb | 8,100 mb/sec
gzip | none | 98% | 16 | 20.8 s | 3.6 gb | 179 mb/sec
none | log msg | 94% | 16 | 15.6 s | 34.5 gb | 2,200 mb/sec
