### ISSUE TITLE
Azos.Web.ContentType.ExtensionToContentType must be configurable

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#45]
It is hard-coded now which is wrong, it also needs to have adefaul, in case
config is not provided it should work out-of-the box

**Comment by zhabis** [comment]
In progress...

**Comment by itadapter** [comment]
e.g. add a App.Counter variable which increments on each read - this is for files, we can do like
`App.Counter-log` where `log` is var name

**Comment by zhabis** [comment]
This should have been ion #48 but it is done
