### ISSUE TITLE
Add "Namespace" and "Type" to Bix attribute to associate Bix GUID with 2 Atoms

### ISSUE THREAD

**Issue by itadapter** [azist/azos#458]
This would allow to map object into a logical namespace and type name with the same attribute. Make them optional.
This is because Bix attribute is needed to establish persistent type identity.
Adding extra attributes like "namespace" and "type" atoms makes sense in Bix identity since it is already used in many places.

The Heap objects may then be found by C# namespace -all implementing decorated with "bix" and driving from Heap.XYZ types...

**Comment by zhabis** [comment]
This has questionable value. Bix does introduce type identity for serialization, but there may be many other attributes needed **for various other-purposes**, e.g. if we have a root `HeapObject`, e.g. `Doctor` it may have a property `Doctor.Name:  NameBlock`, the `NameBlock` does not have a separate "type" identity in a heap, but it does in terms of Bix serializer purposes, hence those two things are **completely orthogonal** although the do coincide sometimes. We should not mix these concepts.
