### ISSUE TITLE
Windows/Linux root host process which works like a service or console app and runs multiple-sub-processes from within

### ISSUE THREAD

**Issue by g8sun** [azist/azos#501]
so we can install on windows service on windows box - and it runs all sub-processes in a similar way to Docker compose

**Comment by g8sun** [comment]
it should provide native WEB/JSON endpoint with detailed status of itself and sub-processes, with or without authorization (depending on config).  Proposing:  use existing app serve host, add a "server" for "Root process" or similar

**Comment by itadapter** [comment]
Related: #502

**Comment by zhabis** [comment]
![image](https://user-images.githubusercontent.com/39680879/124999831-84784200-e03e-11eb-94ad-00712e1feba6.png)

**Comment by g8sun** [comment]
Cluster Testing in progress

**Comment by itadapter** [comment]
done
