### ISSUE TITLE
GovernorSipcClient logs using its own function instead of delegating logging to director, hence the log-level does not work and app logs get flooded with unneeded tracing

### ISSUE THREAD

**Issue by g8sun** [azist/azos#507]

**Comment by itadapter** [comment]
There is no director it can delegate to. It runs BEFORE app starts

**Comment by zhabis** [comment]
Solution. By Defaul log level is now INFO
If you need to change it, set `SKY_HOST_GOVERNOR_LOG_LEVEL` env variable

**Comment by g8sun** [comment]
Its working now
