### ISSUE TITLE
Add EntityId GDID property which is used as address to avoid costly gdid-string conversions, similar optimization was done with ShardKey

### ISSUE THREAD

**Issue by g8sun** [azist/azos#522]
Can add GDID field which gets stored in place of address? however it needs to be serialized so string conversion to address still exists

Maybe add .ctor(atom, atom, gdid) for faster conversion to string?

**Comment by itadapter** [comment]
this contradicts the purpose of the `EntityId`, as if the structure has to work much faster with Gdid - it is not really needed in a first place. Even if we add a field, the conversion to `Address` must take place, and that is what you want to avoid.
Hence, this is a meaningless request.  

**If you need performance that much, create an override which takes GDID as a parameter without using EntityId.**
