### ISSUE TITLE
Rework MySqlCrudQueryHandler<TQueryParamaters> to cast Query.Params to TQueryParameters by making CastParameters virtual

### ISSUE THREAD

**Issue by g8sun** [azist/azos#543]

**Comment by g8sun** [comment]
If TQueryParemeters is Tuple maybe interpret it, otherwise bind first if primitive.
Must allow query with no parameters at all using e.g. AbsentValue as a marker MySqlCrudQueryHandler<AbsentValue>

**Comment by itadapter** [comment]
Impossible to get tuples names. This is compiler-internal feature and the use of `TupleNames` attribute is not deterministic for run-time application. So far we changed `CastParameters` to virtual

**Comment by g8sun** [comment]
in use
