### ISSUE TITLE
Forest- hierarchical tree of configuration data nodes with overrides and full version control (aka Metabiz)

### ISSUE THREAD

**Issue by zhabis** [azist/azos#562]
Metabiz is a hierarchical tree of config files, navigable using string path.
Navigation starts at the top/catalog level, going down using standard path syntax:
```
reg:/us/east/cle/1
```
Each node retains its full history of changes (like Git). Nodes have two dates: version date and apply date, apply date is when node version starts to take logical effect.
Metabiz  stores data in the data store and can handle 100ks of nodes. Data is cached in-memory for faster access.

Metabiz does NOT contain business logic, it only provides configuration content for business applications (hence the name)

**Comment by itadapter** [comment]
Azos.Conf.Metabiz

**Comment by itadapter** [comment]
`Azos/Data/Directory` should be deleted???? What purpose does it serve now?

**Comment by itadapter** [comment]
@JohnPKosh to run TOY, run console **as admin**, the server is on port **8080**:
```console
C:\Zdev\ghub\azos\out\Debug\run-netf>toy wave -config toy-wave.laconf
```
Root URI:
```
http://localhost:8080/conf/forest/tree
```

**Comment by itadapter** [comment]
@JohnPKosh Is the information above sufficient to commence testing?

**Comment by JohnPKosh** [comment]
Yes, I was able to pull latest and verify toy endpoint methods are there and working on my local PC yesterday during the meetings yesterday. Will be working on that today.
