### ISSUE TITLE
ApiDoc fails if there is no `## Endpoints` section

### ISSUE THREAD

**Issue by g8sun** [azist/azos#574]
Controller action body: 'G8.As.Hub.Server.CmsWeb.Doc'.'scope'. Exception: [System.ArgumentOutOfRangeException] Length cannot be less than zero. Parameter name: length

**Comment by zhabis** [comment]
`ApiDocController:273` says `var excision = MarkdownUtils.ExciseSection(scopeContent, "## Endpoints");`

**Comment by itadapter** [comment]
```
 System.ArgumentOutOfRangeException
Length cannot be less than zero. Parameter name: length
Stack:

    at System.String.Substring(Int32 startIndex, Int32 length)
    at Azos.Wave.Mvc.ApiDocController.Scope(String id) in C:\Zdev\ghub\azos\src\Azos.Wave\MVC\ApiDocController.cs:line 333
```
