### ISSUE TITLE
Add OAuth SSO capability with optional Session Context to prevent user re-login on every authorization call

### ISSUE THREAD

**Issue by itadapter** [azist/azos#596]
Re #587  #595

**Comment by g8sun** [comment]
## Request
1. Add `dev-no-https` bool flag to OAuth.Options config section so the session cookie is NOT HTTPS-required
2. Add `cookie-expiration` to OAuth.Options
3. Add `Remember me` check to stock login page
4. Add `suppress-auto-sso-redirect` to not set HTTP MET EQUIV

**Comment by zhabis** [comment]
"logout" is a separate OIDC topic tbd
