### ISSUE TITLE
OAuth SSO Global Logout

### ISSUE THREAD

**Issue by g8sun** [azist/azos#601]
We may need to add `TokenRing` blacklisting capability along with cookie removal

**Comment by g8sun** [comment]
Re: 596

**Comment by zhabis** [comment]
RTM for setcookie part. future: drop access token (Phase II IDP)

**Comment by zhabis** [comment]
The requirement to be an authorized user is wrong. How is the 3rd party supposed to handle that "authorization" since the browser flow is not under its (3rd party) control?

Instead we should check for presence of SSOsession token, and if it is present then reset it, otherwise return 403?

**Comment by zhabis** [comment]
d125c2ad0cff1a687d9b3a59fbe84648f1907e78 nuget 1.42.5.5
