### ISSUE TITLE
MinIdp add CLAIMS key/value pair to user and login entities, add those to MinIdp data as JsonDataMap

### ISSUE THREAD

**Issue by g8sun** [azist/azos#605]

**Comment by itadapter** [comment]
The purpose is to add extra claims like 3rd party system Id for user cross-linking.
I think that claims should come hierarchically in this specific sequence:
```
ROLE -> USER -> LOGIN
```
this way claim data gets cascading down.

As far as data storage, we should probably store these as "Props" not claims, CLAIMS may be a section of props for JWT disclosure as not all claims may be JWT-OIDC dislosable - **this needs design**

**Comment by zhabis** [comment]
93aa68a58080f44c24cada049cc2569f07552730  added `MinIdpData.Props:  ConfigVector`

**Comment by zhabis** [comment]
Need to add the storage to Mogo minidp implementation
