### ISSUE TITLE
[VER MAJOR CHANGE] Collapse many tools under `/run` in one program, driven of a single main argument

### ISSUE THREAD

**Issue by itadapter** [azist/azos#624]
# Need to reduce number of senseless EXEs/dll entry points
 which cloud the out directory
intead of all of the "ntc, rschema etc.." create something like:

```batch
$ azos ntc ....
$ azos rsc ....
$ azos gluec ....
```

## Command Args Notes

In a launch mode with sub-command we need to SKIP the very first argument as "SubCommand"

Maybe add a mode to CommandLineArgs to read the very first argument as config tree root name?
Need to check if CommandLineArgs uses root tree name for anything?

Example:
```
  tool abc 

yields atree

abc
{
  ....
}
```

**Comment by zhabis** [comment]
No need to change command lineArgs, the pivot can be done BEFORE app container body in Main(args)

**Comment by zhabis** [comment]
`sky` needs to use dynamic assembly binding to uncover entry points decorated with "[SkyDriverProcess]" or similar.
The logic needs to be put outside of SKy.exe
