### ISSUE TITLE
Add DateRange along the lines of:

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#68]
//temp placeholder
  [Serializable]
  public struct DateRange : IEquatable<DateRange>
  {
    public static DateRange FromDates(DateTime? start, DateTime? end)
    {
      return new DateRange();
    }

    public static DateRange FromDateTimes(DateTime? start, DateTime? end)
    {
      return new DateRange();
    }

    private DateRange(DateTime? start, DateTime? end)
    {
      Start = start;
      End = end;
    }

    public readonly DateTime? Start;
    public readonly DateTime? End;

    public TimeSpan? Span => null;

    public bool Contains(DateTime date) => false;

    public DateRange Intersect(DateRange other) => new DateRange();

    public bool Equals(DateRange other)
    {
      throw new NotImplementedException();
    }
  }

**Comment by zhabis** [comment]
Done
