### ISSUE TITLE
How to enumerate CacheStore table itens

### ISSUE THREAD

**Issue by rinaldo-rfjr** [azist/azos#690]
Hi.

I'm studying the library in order to use it on a project. I wrote a routine using the CacheStore object to test the store of a large set of data. The problem is that I can't figure how to enumerate the table items, once I have this table filled.

For example, how do I list the table elements whose dates are greater than some value?

That's my test code:

        static void TestCache()
        {
            CacheStore store = new CacheStore();

            try
            {
                var tbl = store["SampleData"]; //This table will be filled with sample data

                for (ulong i = 0; i < 11000000; i++)
                {
                    var sample = new SampleData
                    {
                        Id = Guid.NewGuid(),
                        CreatedAt = DateTime.Now,
                        Value = GetValue(),
                        Period = new Bucket { Month = GetMonth(), Year = GetYear()}
                    };

                    tbl.Put(i, sample);

                    if (i % 1000000 == 0)
                    {
                        CacheRec cr = tbl.Get(i); //How do I find an object by one property, instead of using the key?
                        SampleData sp = (SampleData)cr.Value;
                        Console.WriteLine("Key: " + i.ToString() + " | Period: " + sp.Period.ToString());
                    }
                }

                Console.WriteLine(Environment.NewLine);
                Console.WriteLine("Total: {0} | Pages: {1} | Age: {2} | BucketCount: {3}", tbl.Count, tbl.PageCount, tbl.MaxAgeSec, tbl.BucketCount);

                Console.ReadLine();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.ReadLine();
            }
            finally
            {
                store.Dispose();
            }
        }

Regards,

Rinaldo

**Comment by itadapter** [comment]
@rinaldo-rfjr one can not use ad-hoc searches on hashtable/dictionary structures - it is not possible by design.
If you have a need to support "multiple keys" you can put an item in the different cache tables using different keys.

also, if the set of data is large you should use Azos.Pile.LocalCache instead - it "hides" all references from GC and can significantly improve performance by avoiding GC pauses altogether, however this makes sense if you store like millions of objects, not thousands

**Comment by rinaldo-rfjr** [comment]
Hi @itadapter

I got it.

I tried a code using **LocalCache**, but at some point, the code raises an **OutOfMemory** exception. I see the code generates the files on disk and all goes well, until the exception is thrown. Possibly I'm doing something wrong in the code.

That's the version using **LocalCache**:

`
using NFX;
using NFX.ApplicationModel;
using NFX.ApplicationModel.Pile;
using NFX.DataAccess.Cache;

        static void TestLocalCache()
        {
            Console.WriteLine("Data directory");
            string path = Console.ReadLine();

            var pile = new MMFPile();
            pile.DataDirectoryRoot = path;
            pile.AllocMode = AllocationMode.ReuseSpace;
            pile.Start();

            try
            {
                var cache = new LocalCache("theCache", NOPApplication.Instance);
                cache.Pile = pile;
                cache.Configure(null);
                cache.Start();

                var ta = cache.GetOrCreateTable<long>("SampleCache");
                ta.Options.CollisionMode = CollisionMode.Durable;
                ta.Options.MaximumCapacity = 0;

                for (long i = 0; i < 500000000; i++)
                {
                    var sample = new SampleData
                    {
                          Id = Guid.NewGuid(),
                         CreatedAt = DateTime.Now,
                         Value = GetValue(),
                         Period = new Bucket { Month = GetMonth(), Year = GetYear()}
                    };

                    ta.Put(i, sample);

                    if (i % 500000 == 0)
                    {
                        var s = ta.Get(i) as SampleData;
                        Console.WriteLine("Key: " + i.ToString());
                    }
                }

                cache.WaitForCompleteStop();
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.ReadLine();
            }
            finally
            {
                DisposableObject.DisposeAndNull(ref pile);
                //pile.Dispose();
            }
        }
`

My application is a .net 4.8 application. Can I use the new Azos library on it, or is it only for new .net 5.0 applications?

Regards,

Rinaldo

**Comment by zhabis** [comment]
Dont use MMFPile - it writes to disk. Use DefaultPile which keeps data in memory and much faster.
Yes, you should be able to use Azos with 4.8
As far as search - a cache searches by one key by design. Use database if you need indexes
