### ISSUE TITLE
[vNEXT] Migrate .NET 6

### ISSUE THREAD

**Issue by zhabis** [azist/azos#723]

**Comment by zhabis** [comment]
![image](https://user-images.githubusercontent.com/39680879/185510457-5d306c3c-3080-4af5-b57f-8654150b99bd.png)

**Comment by zhabis** [comment]
![image](https://user-images.githubusercontent.com/39680879/185510847-8455159d-56d2-493c-a97b-dd728e9bb5f6.png)

**Comment by itadapter** [comment]
![image](https://user-images.githubusercontent.com/2273574/185758308-a04b2a94-ea29-4459-99d2-afe522c9a996.png)
