### ISSUE TITLE
AuthKit DefaulIdoHandlerLogic.ApplyEffectivePoliciesAsync must read role conf and take rights from `/rights` path, as conf may have OTHER confg parameters pertaining to the role tree level

### ISSUE THREAD

**Issue by zhabis** [azist/azos#803]

**Comment by itadapter** [comment]
Problem is with this:
The tree root is P and R, whereas children are P{ROPS and CONF - we MUST standardize root node names
![image](https://user-images.githubusercontent.com/2273574/200965058-6b3a8955-2c46-4df8-96f9-aa066745c3e2.png)

**Comment by zhabis** [comment]
It works after root node fix. We need to standardize root node names
![image](https://user-images.githubusercontent.com/39680879/200965820-3a2adf82-6ed3-4699-8fcc-55ab5c2c0845.png)

**Comment by itadapter** [comment]
done
