### ISSUE TITLE
Azure.Identity looking for version 1.7 , even though dependency in project is for version 1.8

### ISSUE THREAD

**Issue by amitverma009** [azist/azos#825]
Hi All,

I am facing this strange issue where  my project is referring to nuget Microsoft.Data.SqlClient 5.1.0 which has a dependency on Azure.Identity > 1.7 .

My project is also referring to nuget Azure.Identity 1.8 . 

So in project dependencies I have azure.Identity 1.8 and project is building with the same.

Issue : At runtime code is looking for version of Azure.Identity as 1.7 as failing.

Project is a windows service running on .NET Framework 4.7.2.

Any help will be really appreciated.

Regards
Amit

**Comment by itadapter** [comment]
@amitverma009 The problem is most likely with Microsoft.Data.SqlClient.dll  which never determines the proper version for the output; Azos does not use Azure.Identity; what component of Azos are you trying to use?

**Comment by amitverma009** [comment]
thanks  .. Seems like you are right the issue is with SQlClient.dll ..
