### ISSUE TITLE
seems to lack search engine support in Azos includes(ReadMe.md).

### ISSUE THREAD

**Issue by sgf** [azist/azos#916]
What are the plans for the search engine? will use Elasticsearch developed in Java? Or consider lucene.net of the .net technology stack (which is obviously much behind).

**Comment by itadapter** [comment]
Why not use Elasticsearch? Just a webservice with HTTP API. No need for client. Use rest directly via HttpClient lib

**Comment by sgf** [comment]
> Unique feature of Azos is its **self-sufficiency** as it includes **all of the components** necessary for creation of typical business to Facebook-scale applications.

 **self-sufficiency**   **all of the components** 
I thought it was true
