### ISSUE TITLE
Add API Documentation capability

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#95]
- Provide metadata as Configuration object in XML/JSOn/LACONIC formats
- Ability to-mix-in Markdown Section content using simple attributes on the endpoint level
- probably needs IApiMetadataProvider then implement it on action filter attributes,

```csharp
    [ApiDoc("#section")]
    [ActionOnGet(Name = "list"), AcceptsJson]
    public object ListGet() => Schema.GetForTypedDoc<MemberListFilter>();
```

**Comment by erxdkh** [comment]
Add to controller:
```csharp
[ApiDoc(MountUri="/mount/point/")]
public class Controller
{
}
```

**Comment by zhabis** [comment]
see APIDocs as in ApiControllerDoc, ApiEndpointDoc attributes

**Comment by zhabis** [comment]
DONE
